name: "Clair Build"
description: "Create a PostgreSQL image with scan vulnerability"

inputs:
  local:
    description: 'It tells if the container image is deployed localy or remote. Values: yes | no'
    required: false
    default: 'yes'
  clair_timeout:
    description: 'Establish the timeout in seconds while waiting for Clair to be ready, useful for slower runners'
    required: false
    default: 120
  updater:
    description: 'Set Updater E.G. debian'
    required: true
    
runs:
  using: "composite"
  steps:
    - run: |
        sed -i 's/SET_UPDATER/${{ inputs.updater }}/g' $GITHUB_ACTION_PATH/config.yaml
        chmod +x $GITHUB_ACTION_PATH/run.sh && $GITHUB_ACTION_PATH/run.sh ${{inputs.clair_timeout}}
      shell: bash
