name: Build PostgreSQL Clair

on: [push]
       
jobs:  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.USER_PAT }}
      - name: Start PostgreSQL and clair
        uses: the-iron-bank-of-braavos/postgres-clair@master
        with:
          clair_timeout: 3600
