name: Build PostgreSQL Clair

on: [push]
       
jobs:  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.USER_PAT }}
      - name: Start PostgreSQL and clair
        uses: the-iron-bank-of-braavos/postgres-clair@master
        with:
          clair_timeout: 3600
  trivy-image-scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          #image-ref: 'vulnerables/web-dvwa:latest'
          image-ref: 'ghcr.io/the-iron-bank-of-braavos/postgres-clair/postgres:clair'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
