name: Build PostgreSQL Clair

on: [push]
       
jobs:  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Start PostgreSQL and clair
        uses: the-iron-bank-of-braavos/postgres-clair@master
        with:
          clair_timeout: 1800
