name: Trivy Image Scan

on: [pull_request]
       
jobs:  
  build:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          #image-ref: 'vulnerables/web-dvwa:latest'
          image-ref: 'ghcr.io/the-iron-bank-of-braavos/postgres-clair/postgres:clair'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
